{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T07:50:07.517Z"}
{"level":"error","message":"Registration error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async register (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\auth.controller.ts:14:24)","timestamp":"2025-04-22T07:56:35.166Z"}
{"level":"error","message":"500 - SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string - /api/auth/register - POST - ::ffff:127.0.0.1","timestamp":"2025-04-22T07:56:35.170Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T07:57:33.427Z"}
{"level":"error","message":"Registration error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async register (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\auth.controller.ts:14:24)","timestamp":"2025-04-22T07:58:15.560Z"}
{"level":"error","message":"500 - SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string - /api/auth/register - POST - ::ffff:127.0.0.1","timestamp":"2025-04-22T07:58:15.562Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T08:01:55.325Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T08:02:10.533Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:02:28.234Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:04:12.115Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:04:59.339Z"}
{"code":"42703","file":"analyze.c","length":140,"level":"error","line":"2536","message":"Forgot password error: column \"reset_password_token\" of relation \"users\" does not exist","name":"error","position":"26","routine":"transformUpdateTargetList","severity":"ERROR","stack":"error: column \"reset_password_token\" of relation \"users\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async forgotPassword (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\auth.controller.ts:157:5)","timestamp":"2025-04-22T08:04:59.390Z"}
{"level":"error","message":"500 - column \"reset_password_token\" of relation \"users\" does not exist - /api/auth/forgot-password - POST - ::ffff:127.0.0.1","timestamp":"2025-04-22T08:04:59.397Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:05:31.046Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:36:46.727Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:54:41.154Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:55:19.120Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:59:04.556Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T08:59:32.547Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T09:07:54.869Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T10:56:11.471Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T11:03:36.316Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T11:08:46.222Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T11:44:39.009Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T11:44:53.269Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T11:49:12.415Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T12:04:15.236Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T12:32:04.396Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T12:38:55.821Z"}
{"level":"info","message":"Updated profile details for user 3","timestamp":"2025-04-22T12:38:55.927Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async updateProfile (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:176:7)","timestamp":"2025-04-22T12:38:56.003Z"}
{"level":"info","message":"Profile update committed for user 3","timestamp":"2025-04-22T12:38:56.007Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T12:38:56.196Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T12:57:18.981Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T12:58:16.085Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-22T13:10:03.573Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:27:40.518Z"}
{"level":"info","message":"Updated profile details for user 3","timestamp":"2025-04-22T14:27:40.690Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async updateProfile (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:176:7)","timestamp":"2025-04-22T14:27:40.798Z"}
{"level":"info","message":"Profile update committed for user 3","timestamp":"2025-04-22T14:27:40.902Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:27:41.272Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:27:47.512Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:28:17.184Z"}
{"level":"info","message":"Resume 1 uploaded and set as default for user 3","timestamp":"2025-04-22T14:28:17.264Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:28:17.476Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:17.483Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:17.493Z"}
{"level":"info","message":"Deleted orphaned resume file after DB error: C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\uploads\\resumeFile-1745332096810-472174871.pdf","timestamp":"2025-04-22T14:28:17.497Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:17.499Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:28:17.510Z"}
{"level":"info","message":"Resume 2 uploaded and set as default for user 3","timestamp":"2025-04-22T14:28:19.560Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:28:20.032Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:20.040Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:20.048Z"}
{"level":"info","message":"Deleted orphaned resume file after DB error: C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\uploads\\resumeFile-1745332099539-593258384.pdf","timestamp":"2025-04-22T14:28:20.060Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:20.074Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:28:20.082Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:28:39.478Z"}
{"level":"info","message":"Resume 3 uploaded and set as default for user 3","timestamp":"2025-04-22T14:28:39.500Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:28:39.741Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:39.744Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:39.747Z"}
{"level":"info","message":"Deleted orphaned resume file after DB error: C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\uploads\\resumeFile-1745332118673-425555291.pdf","timestamp":"2025-04-22T14:28:39.752Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:39.761Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:28:39.764Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:29:03.330Z"}
{"level":"info","message":"Resume 4 uploaded and set as default for user 3","timestamp":"2025-04-22T14:29:03.356Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:29:03.573Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:03.579Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:03.583Z"}
{"level":"info","message":"Deleted orphaned resume file after DB error: C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\uploads\\resumeFile-1745332142988-765128401.pdf","timestamp":"2025-04-22T14:29:03.588Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:03.603Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:29:03.608Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:29:32.265Z"}
{"level":"info","message":"Resume 5 uploaded and set as default for user 3","timestamp":"2025-04-22T14:29:32.296Z"}
{"level":"info","message":"Connected to PostgreSQL database","timestamp":"2025-04-22T14:29:32.516Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:32.520Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:32.524Z"}
{"level":"info","message":"Deleted orphaned resume file after DB error: C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\uploads\\resumeFile-1745332172022-458477360.pdf","timestamp":"2025-04-22T14:29:32.527Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:32.531Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:29:32.537Z"}
{"level":"info","message":"Server running on port 5000","timestamp":"2025-04-23T14:52:58.347Z"}
{"level":"info","message":"Server running on port 3000","timestamp":"2025-04-24T13:53:08.066Z"}
