{"level":"error","message":"Registration error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async register (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\auth.controller.ts:14:24)","timestamp":"2025-04-22T07:56:35.166Z"}
{"level":"error","message":"500 - SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string - /api/auth/register - POST - ::ffff:127.0.0.1","timestamp":"2025-04-22T07:56:35.170Z"}
{"level":"error","message":"Registration error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async register (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\auth.controller.ts:14:24)","timestamp":"2025-04-22T07:58:15.560Z"}
{"level":"error","message":"500 - SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string - /api/auth/register - POST - ::ffff:127.0.0.1","timestamp":"2025-04-22T07:58:15.562Z"}
{"code":"42703","file":"analyze.c","length":140,"level":"error","line":"2536","message":"Forgot password error: column \"reset_password_token\" of relation \"users\" does not exist","name":"error","position":"26","routine":"transformUpdateTargetList","severity":"ERROR","stack":"error: column \"reset_password_token\" of relation \"users\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async forgotPassword (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\auth.controller.ts:157:5)","timestamp":"2025-04-22T08:04:59.390Z"}
{"level":"error","message":"500 - column \"reset_password_token\" of relation \"users\" does not exist - /api/auth/forgot-password - POST - ::ffff:127.0.0.1","timestamp":"2025-04-22T08:04:59.397Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async updateProfile (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:176:7)","timestamp":"2025-04-22T12:38:56.003Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async updateProfile (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:176:7)","timestamp":"2025-04-22T14:27:40.798Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:17.483Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:17.493Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:17.499Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:28:17.510Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:20.040Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:20.048Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:20.074Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:28:20.082Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:39.744Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:39.747Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:28:39.761Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:28:39.764Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:03.579Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:03.583Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:03.603Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:29:03.608Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Update profile completion error for user 3: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:32.520Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Resume upload rolled back for user 3 due to error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:32.524Z"}
{"code":"42P01","file":"parse_relation.c","length":115,"level":"error","line":"1452","message":"Upload resume error: relation \"user_experiences\" does not exist","name":"error","position":"40","routine":"parserOpenTable","severity":"ERROR","stack":"error: relation \"user_experiences\" does not exist\n    at C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\node_modules\\pg-pool\\index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async updateProfileCompletion (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:1057:27)\n    at async uploadResume (C:\\Users\\urban\\Documents\\Teach2giveFinal\\skillMatchAi-backend\\src\\controllers\\user.controller.ts:303:9)","timestamp":"2025-04-22T14:29:32.531Z"}
{"level":"error","message":"500 - relation \"user_experiences\" does not exist - /api/users/resumes - POST - ::1","timestamp":"2025-04-22T14:29:32.537Z"}
